name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: [self-hosted, linux]

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
           docker rm -f osz
           docker build . --file Dockerfile --tag osz
           docker run -p 3010:80 --name osz -d osz
           
